name: context-demo
'on': push
jobs:
  context-demo: 
    runs-on: ubuntu-latest
    steps:
      -name: Use context variable
        run: |
          echo "Triggered by ${{ github.actor }}"
          echo "Repo name ${{ github.repo }}"
